### ISSUE TITLE
Crossdomain access denied - problem

### ISSUE THREAD

**Issue by elbagus** [veldjmaxis/plugins-video-telewizjada#1]
Przetestowałem sobie playlisty wygenerowane przez ten skrypt, ale żadne nie chcą się otworzyć. W tym celu wykorzystałem odtwarzacz na stronie https://www.hlsplayer.net/, który za każdym razem wyrzuca kod błędu z komunikatem "Cannot load M3U8: crossover access denied...". W aplikacji Smart IPTV dla Tizen w Samsungach również dany kanał nie otwiera się. Próbowałem użyć więc najzwyklejszego przekierowania do uzyskanego adresu chunklisty, zamiast generowania pliku .m3u8, ale nic mi to nie dało. Na innym skrypcie, który wynalazłem gdzieś w Google, dzieje się to samo.

Przyczyną jest najwidoczniej plik, który znajduje się pod adresem *.telewizjada.net/crossdomain.xml.
Jego zawartość wygląda wtedy następująco:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
    <allow-access-from domain="*.telewizjada.net" secure="false"/>
    <allow-access-from domain="telewizjada.net" secure="false"/>
    <allow-access-from domain="*.polwizjer.com" secure="false"/>
    <allow-access-from domain="polwizjer.com" secure="false"/>
    <site-control permitted-cross-domain-policies="all"/>
</cross-domain-policy>
```

Czy można to jakoś obejść?

**Comment by veldjmaxis** [comment]
Obejście zrobione. Dodany został dodatkowy główek reprezentujący host łączący się z serwerem. Proszę o pobranie najnowszego wydania i info czy jest ok.
Temat czasowo zamykam.
